### ISSUE TITLE
Homepage + login form

### ISSUE THREAD

**Issue by resir014** [kawalcovid19/silacak#11]
### Mobile [priority: high]

[Figma link](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=12%3A1362)
![image](https://user-images.githubusercontent.com/12446260/128643059-93257372-8cd8-4d86-81b6-81061a6c1940.png)

### Desktop 

[Figma link](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=4%3A2)
![image](https://user-images.githubusercontent.com/12446260/128643005-6daf6598-d797-483c-bff2-f3671dfcd1c8.png)

**Comment by ramarahmanda** [comment]
## Homepage/Login

### Mobile [priority: high]
click [here](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=12%3A1362) to see figma link
![image](https://user-images.githubusercontent.com/12446260/128643059-93257372-8cd8-4d86-81b6-81061a6c1940.png)

### Desktop 
click [here](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=4%3A2) to see figma link
![image](https://user-images.githubusercontent.com/12446260/128643005-6daf6598-d797-483c-bff2-f3671dfcd1c8.png)
