### ISSUE TITLE
Tracer Registration Form

### ISSUE THREAD

**Issue by resir014** [kawalcovid19/silacak#12]
## Description

![Pendaftaran](https://user-images.githubusercontent.com/6219895/128629986-8f27849c-b0c1-471e-8b90-33075696feab.png)

### Figma Links

- [Mobile](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=12%3A1458)
- [Desktop](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=4%3A1450)

Todo:

1. [ ] Content board container
2. [ ] Form title
3. [ ] Form text input
4. [ ] Form text input with prefix
5. [ ] Form select input
6. [ ] Form radio button input
7. [ ] Form validation label
8. [ ] Form password input
9. [ ] Button
10. [ ] Info message component

**Comment by adityapurwa** [comment]
Can I help with this one? 🙌

**Comment by ramarahmanda** [comment]
### Figma Url
- [Mobile](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=12%3A1458)
- [Desktop](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=4%3A1450)
