### ISSUE TITLE
Add `security.txt` file to make it easier for security researchers to submit security vulnerability reports

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/silacak#25]
## Description

It's a copy of kawalcovid19/wargabantuwarga.com#482

The main purpose of `security.txt` is to help make things easier for companies and security researchers when they want to get in touch with us about security issues.

The https://securitytxt.org/ website provides a generator for the `security.txt` file as well as a FAQ, and the technical standard (draft) can be viewed [here](https://tools.ietf.org/html/draft-foudil-securitytxt-12).

## Implementation Model

- Generate a `security.txt` file using https://securitytxt.org/ - make sure that the email used for this text file is active *and* secure.
- Make sure to set an expiration period for the `security.txt` to be 1 year at the latest. We need to also make sure that these credentials get properly rotated when we need to renew these details.
- Place the `security.txt` file in the `.well-known` folder of our root site directory: `public/.well-known/security.txt`

## Tasks

- [ ] Generate the `security.txt` file using the requirements listed above.

**Comment by asaadam** [comment]
if we want to make file security, it needs an email registered to be contacted. 
therefore, who’s email will be registered?
![image](https://user-images.githubusercontent.com/1397612/128866091-057fec2c-fe99-4729-a8e6-6e78e1210020.png)

**Comment by zainfathoni** [comment]
Please use `admin@kawalcovid19.id` email for that. We're using the same email in our [CODE_OF_CONDUCT.md](https://github.com/kawalcovid19/silacak/blob/main/CODE_OF_CONDUCT.md#enforcement).
