### ISSUE TITLE
Check activation account

### ISSUE THREAD

**Issue by ramarahmanda** [kawalcovid19/silacak#28]
## Description

![Check account activation](https://user-images.githubusercontent.com/12446260/128891741-8210b56b-953d-4207-9873-55676ce18223.png)

### Figma Links

- [Mobile](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=189%3A2074)
- [Desktop](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=143%3A2810)
- [Prototype](https://www.figma.com/proto/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=143%3A2810&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=4%3A2&hide-ui=1)

Todo:

1. [ ] Add button in login page to redirect to check activation account page
2. [ ] Form title
3. [ ] Form text input
4. [ ] Form button check
5. [ ] Message Error user is not activated
6. [ ] Message Error user not found
7. [ ] Message Success user is activated

**Comment by zainfathoni** [comment]
@all-contributors please add @ramarahmanda for project management and ideas.
