### ISSUE TITLE
Close Contact - Detail

### ISSUE THREAD

**Issue by auliazahrina** [kawalcovid19/silacak#37]
## Description

This page displays the detail of a close contact case. This page can be accessed by clicking "Lihat Detil" on close contact list in confirmed case detail [(this page)](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=130%3A1315)

Figma: [https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=238%3A3085](https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=238%3A3085)
Prototype: https://www.figma.com/proto/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=238%3A3085&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=4%3A2&hide-ui=1

## Tasks

- [ ] Display close contact details

**Comment by hanihusam** [comment]
Where should I locate this page? `pages/dashboard/close-contact/[contactDetailSlug]/`?

**Comment by zainfathoni** [comment]
What do you think, @resir014?

Shall we create the placeholder pages to easily communicate to our contributors which path we should use for each page?

**Comment by resir014** [comment]
@hanihusam @zainfathoni Let's wait until #62 is done.

**Comment by zainfathoni** [comment]
Since #62 is done last night, now you should know where this page's route is supposed to be @hanihusam. You can start working on it if you want. 😉
