### ISSUE TITLE
Panduan, faq, and registration-status pages could not be found

### ISSUE THREAD

**Issue by dekwahdimas** [kawalcovid19/silacak#67]
## Description

Three pages could not be found. This pages include ```/panduan```, ```/faq```, and ```/registration-status```

## Expected Behaviour

It should show the pages as it should.

## Screenshots

<details>
<summary>Here's the screenshots</summary>

### /panduan
![Screenshot (177)](https://user-images.githubusercontent.com/56619123/129891735-a2eb9cd4-4f86-4026-a1c6-186c91cd32ab.png)

### /faq
![Screenshot (175)](https://user-images.githubusercontent.com/56619123/129891298-1f27c153-1606-41a3-86e1-c40a4fc63bac.png)

### /registration-status
![Screenshot (176)](https://user-images.githubusercontent.com/56619123/129891315-fd35f23c-8891-4f67-b3e2-d1209feefec8.png)

</details>

**Comment by dekwahdimas** [comment]
I just checked the code. It's not available yet right? My bad :flushed:

But, isn't it better if we don't show these pages on heading until the pages already launch?

**Comment by resir014** [comment]
Please refer to #8 for now. We're still working on the layout MVP.
