### ISSUE TITLE
Mobile drawer gives error when clicking between Tracing and Monitoring menu item

### ISSUE THREAD

**Issue by resir014** [kawalcovid19/silacak#76]
## Description

When switching between the Tracing and Monitor pages using the mobile drawer, the entire page errors out with the following error in the console.

```
Uncaught Error: There are no focusable elements inside the <FocusTrap />

[...]

The above error occurred in the <Dialog> component:

[...]
```

**Demo video**

https://user-images.githubusercontent.com/5663877/130315419-5464e154-5ff4-41fa-b6ec-b2ff90d2240e.mp4

(🎵 Robert Maxwell - Nature Boy)

## Expected Behaviour

The mobile drawer should work as expected.

## Additional Information

This error might occur due to how we implement the dashboard header. [As per the Headless UI docs](https://headlessui.dev/react/dialog#managing-focus-within-your-dialog), the `Dialog` component needs at least one focusable element (e.g. `<a>`, `<button>`). Hence, we need to revisit our [mobile navigation implementation](https://tailwindui.com/components/application-ui/application-shells/sidebar#component-9899e7dd65f66e9a3ee78e7bb1abdeaa) at `dashboard-sidebar.tsx`.

Could it be because we forgot to close the sidebar when the route changes? If so, we should do [something like this](https://github.com/kawalcovid19/wargabantuwarga.com/blob/main/components/layout/navigation-menu.tsx#L39-L51) and change the drawer's open state before the route changes.

Should we also explicitly set the initial focus element on the `Dialog` component? If so, we should implement it as shown here:

![image](https://user-images.githubusercontent.com/5663877/130315800-1ea28743-f53d-42e2-b647-8649a312b5b2.png)

**Comment by adibfirman** [comment]
Hi @resir014 I will try to pick up this issue ya
